<?php

declare(strict_types=1);

namespace AlfacodeTeam\Ground;

/**
 * Everything a plugin needs before it can be tested — written once, in order.
 *
 * ─── WHAT IS COMMITTED, AND WHAT IS NOT ─────────────────────────────────────
 *
 * The split is the point of this class, and it is not "generated vs written by
 * hand". It is **is this a property of the PLUGIN, or of this MACHINE?**
 *
 *   committed   phpunit.xml, tests/, ui/__tests__/, ui/__fixtures__/
 *               These ARE the plugin's tests. A checkout with no phpunit.xml
 *               cannot run them, so CI would be testing nothing.
 *
 *   ignored     vendor/, composer.local.*, ground.databases.json,
 *               docker-compose.ground.yml, ui/node_modules/,
 *               ui/package.json, ui/vitest.config.ts, .phpunit.cache/
 *               Every one names a path, a port or a password that exists on
 *               one developer's machine. Committing them publishes credentials
 *               and hands the next developer a config pointing at servers they
 *               do not have — so their run fails for a reason that has nothing
 *               to do with the plugin.
 *
 * The ignore entries are written FIRST. If the run dies halfway, the worst case
 * is files that are already ignored rather than a `git add -A` that commits a
 * database password.
 */
final class Init
{
    /**
     * Local-only paths, with the reason each is local.
     *
     * Kept as one list so the .gitignore block and this class's own
     * documentation cannot drift apart.
     */
    public const IGNORED = [
        '/vendor/'                   => 'installed dependencies',
        'composer.local.json'        => 'local dev manifest (bin/link-local)',
        'composer.local.lock'        => 'local dev manifest (bin/link-local)',
        '.phpunit.cache/'            => 'phpunit result cache',
        '.phpunit.result.cache'      => 'phpunit result cache',
        '.env'                       => 'local env for `ground` — may hold real keys',
        'ground.databases.json'      => 'database hosts + PASSWORDS for `ground migrate`',
        'docker-compose.ground.yml'  => 'local database servers',
        '/node_modules/'             => 'installed frontend dependencies',
        '/ui/node_modules/'          => 'installed frontend dependencies',
        '/ui/package.json'           => 'generated by `ground new ui-test --config`',
        '/ui/package-lock.json'      => 'generated by npm install',
        '/ui/yarn.lock'              => 'generated by yarn install',
        '/ui/pnpm-lock.yaml'         => 'generated by pnpm install',
        '/ui/vitest.config.ts'       => 'generated; its aliases are this machine\'s checkouts',
        '/ui/tsconfig.plugins.json'  => 'generated alias stub for the shared UI kit',
        '/ui/.ground/'               => 'generated dev server workspace (`ground dev`)',
        '/ui/dist/'                  => 'vite build output',
        '/ui/.vite/'                 => 'vite dependency cache',
    ];

    /** @var list<string> */
    private array $wrote = [];

    /** @var list<string> */
    private array $kept = [];

    public function __construct(
        private readonly string $pluginDirectory,
        private readonly string $pluginName,
    ) {}

    /** @return list<string> */
    public function wrote(): array
    {
        return $this->wrote;
    }

    /** @return list<string> */
    public function kept(): array
    {
        return $this->kept;
    }

    /**
     * Add every local-only path to .gitignore, and say which were added.
     *
     * @return list<string> the entries this call appended
     */
    public function ignoreLocalFiles(): array
    {
        $path     = $this->pluginDirectory . '/.gitignore';
        $existing = is_file($path) ? (string) file_get_contents($path) : '';
        $missing  = [];

        foreach (array_keys(self::IGNORED) as $entry) {
            if (!$this->ignoresLine($existing, $entry)) {
                $missing[] = $entry;
            }
        }

        if ($missing === []) {
            return [];
        }

        $block = ($existing === '' || str_ends_with($existing, "\n") ? '' : "\n")
            . "\n# ── Local test harness (`hkm ground init`) ──────────────────────────\n"
            . "# Machine-specific, regenerable, and some of it holds credentials.\n"
            . "# The TESTS themselves (tests/, ui/__tests__, ui/__fixtures__) are\n"
            . "# source and belong in git — only the scaffolding below does not.\n";

        // The comment goes on its OWN line. `.gitignore` has no inline
        // comments — a trailing `# why` is part of the PATTERN, so
        // `ground.databases.json  # holds passwords` matches a file literally
        // named that, and the real one stays committable. Verified with
        // `git check-ignore`, which is the only thing that actually knows.
        foreach ($missing as $entry) {
            $block .= '# ' . self::IGNORED[$entry] . "\n" . $entry . "\n";
        }

        file_put_contents($path, $existing . $block);

        return $missing;
    }

    /** The PHPUnit config — committed: without it a CI checkout tests nothing. */
    public function phpunitConfig(): void
    {
        $suite = $this->studly($this->pluginName);

        $this->write('phpunit.xml', <<<XML
        <?xml version="1.0" encoding="UTF-8"?>
        <phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
                 bootstrap="vendor/autoload.php"
                 colors="true"
                 failOnWarning="true"
                 failOnRisky="true"
                 cacheDirectory=".phpunit.cache">
            <testsuites>
                <testsuite name="{$suite}">
                    <directory>tests</directory>
                </testsuite>
            </testsuites>
            <source>
                <include>
                    <directory suffix=".php">.</directory>
                </include>
                <exclude>
                    <directory>tests</directory>
                    <directory>vendor</directory>
                    <directory>database</directory>
                    <directory>ui</directory>
                </exclude>
            </source>
        </phpunit>

        XML);
    }

    /**
     * A CI workflow that runs the whole bench.
     *
     * Committed, because it is how the plugin is verified by anyone who is not
     * on this laptop — and it is the only place the real databases are
     * guaranteed to exist, through service containers.
     */
    public function ciWorkflow(): void
    {
        $this->write('.github/workflows/ground.yml', <<<'YAML'
        # Generated by `hkm ground init`.
        #
        # The service containers are the point: `ground migrate --strict` fails
        # when a supported database was NOT exercised, so CI cannot go green by
        # quietly testing SQLite alone the way a laptop does.
        name: ground

        on: [push, pull_request]

        jobs:
          bench:
            runs-on: ubuntu-latest

            services:
              mysql:
                image: mysql:8.4
                env: { MYSQL_ROOT_PASSWORD: ground }
                ports: ["3306:3306"]
                options: >-
                  --health-cmd="mysqladmin ping -h 127.0.0.1 -pground"
                  --health-interval=3s --health-retries=20
              postgres:
                image: postgres:17
                env: { POSTGRES_PASSWORD: ground }
                ports: ["5432:5432"]
                options: >-
                  --health-cmd="pg_isready -U postgres"
                  --health-interval=3s --health-retries=20

            env:
              # Env beats ground.databases.json, which is gitignored and absent here.
              GROUND_DB_MYSQL: mysql://root:ground@127.0.0.1:3306
              GROUND_DB_PGSQL: pgsql://postgres:ground@127.0.0.1:5432

            steps:
              - uses: actions/checkout@v4

              - uses: shivammathur/setup-php@v2
                with:
                  php-version: "8.4"
                  extensions: pdo_mysql, pdo_pgsql, pdo_sqlite, mbstring, intl

              - run: composer install --no-interaction --prefer-dist

              - name: Static checks
                run: vendor/bin/ground check --here

              - name: Tests
                run: vendor/bin/phpunit

              - name: Migrations, on every database
                run: vendor/bin/ground migrate --strict

        YAML);
    }

    /** Does this plugin already have somewhere to put tests? */
    public function hasTests(): bool
    {
        return is_dir($this->pluginDirectory . '/tests')
            && glob($this->pluginDirectory . '/tests/*.php') !== [];
    }

    public function hasMigrations(): bool
    {
        foreach (['database/migrations', 'database/tenant-template'] as $rel) {
            if (glob($this->pluginDirectory . '/' . $rel . '/*.php') !== []) {
                return true;
            }
        }

        return false;
    }

    // ── Internals ─────────────────────────────────────────────────────────────

    private function write(string $relative, string $contents): void
    {
        $path = $this->pluginDirectory . '/' . $relative;

        if (is_file($path)) {
            $this->kept[] = $relative;

            return;
        }

        $dir = \dirname($path);

        if (!is_dir($dir) && !mkdir($dir, 0o755, true) && !is_dir($dir)) {
            return;
        }

        file_put_contents($path, $contents);
        $this->wrote[] = $relative;
    }

    /**
     * Whole-line match.
     *
     * A substring test would consider `ground.databases.json` already ignored
     * because some unrelated line happens to contain the word `ground`, and the
     * file holding the passwords would stay committable.
     */
    private function ignoresLine(string $haystack, string $needle): bool
    {
        $wanted = trim($needle, '/');

        foreach (explode("\n", $haystack) as $line) {
            $line = trim(explode('#', $line, 2)[0]);

            if ($line !== '' && trim($line, '/') === $wanted) {
                return true;
            }
        }

        return false;
    }

    private function studly(string $value): string
    {
        $value = preg_replace('/[^a-zA-Z0-9]+/', ' ', $value) ?? $value;

        return str_replace(' ', '', ucwords(trim($value))) ?: 'Plugin';
    }
}
